"""Add sensationalism fields

Revision ID: a222917a1dfd
Revises: 001
Create Date: 2025-12-06 12:25:15.608542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a222917a1dfd'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('sensationalism_score', sa.Float(), nullable=True))
    op.add_column('article', sa.Column('sensationalism_explanation', sa.VARCHAR(), nullable=True))
    op.add_column('article', sa.Column('analysis_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'analysis_metadata')
    op.drop_column('article', 'sensationalism_explanation')
    op.drop_column('article', 'sensationalism_score')
    # ### end Alembic commands ###
